### ISSUE TITLE
this line not returning String. What i do? String translationResult = translatorBackgroundTask.execute(textToBeTranslated,languagePair);

### ISSUE THREAD

**Issue by ahsan7766** [DoguD/Yandex-Translate-Android-API#2]
i want to get result here but i m not actually able to load the class
String translationResult = translatorBackgroundTask.execute(textToBeTranslated,languagePair);
when i convert it to string and run.
it shows result as:
Translation Result: com.example.application.TranslatorBackgroundTask@2af6dbf1

if(Locale.getDefault().getLanguage().contentEquals("zh"))
        {
            String languagePair = "en-zh"; //English to chinese ("<source_language>-<target_language>")
            //Executing the translation function
            Translate(message,languagePair);
            textView.setText(translationResult);
        }

**Comment by DoguD** [comment]
Could you please send me the whole **.java** file which you are trying to call the Translate function?

**Comment by DoguD** [comment]
Could you please try
`String translationResult = translatorBackgroundTask.execute(textToBeTranslated,languagePair).get();`

**Comment by guibas741** [comment]
I am having the same problem, could you help me? I tried the `.get()` but it didnt work

**Comment by guibas741** [comment]
` btnTraduzir.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) { `
                
               ` String textToBeTranslated = "Hello world, yeah I know it is stereotype.";
                String languagePair = "en-fr";
                
                Translate(textToBeTranslated,languagePair); 
                
            }
        });
}



    void Translate(String textToBeTranslated,String languagePair){
        TranslatorBackgroundTask translatorBackgroundTask= new TranslatorBackgroundTask(getApplicationContext());
        String translationResult = null; // Returns the translated text as a String
        try {
            translationResult = translatorBackgroundTask.execute(textToBeTranslated,languagePair).get();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
        Log.d("Translation Result",translationResult); 
    } `

**Comment by guibas741** [comment]
If i dont use the `get()` this is what i get: 
`Change variable 'translationResult' type to 'android.os.AsyncTask<java.lang.String,java.lang.Void,java.lang.String>' ` 

or 
`Migrate 'translationResult' type to 'android.os.AsyncTask<java.lang.String,java.lang.Void,java.lang.String>'`

or `Wrap using 'String.valueOf'`

but none of these worked

**Comment by dayvsonsales** [comment]
@guibas741 this library is very simple. Using get() result will give you the json returned by API call. I had the same problem of yours and I solved doing some modifications in the library. I created a interface and implemented it in MainActivity to ensure that real result will be got. Second, I moved the last lines of doInBackground method (whom "humanize" json result) to onPostExecute. Lastly, I called the MainActivity`s implemented method in the onPostExecute, passing the final result.

**Comment by DoguD** [comment]
@dayvsonsales a pull request from you will be appreciated.
